### PR TITLE
add polymorphic relations

### PR DESCRIPTION
**Pull request by tkellen**
O_o why people do this I will never understand.

### CODE REVIEW

**Comment by bobholt** [comment]
This doesn't appear to be heterogeneous in the way json-api expects. Unfortunately, the only example of possibly expected behavior I can find is in this issue by @dgeb: https://github.com/json-api/json-api/issues/348.

Based on that, these are the issues I see with polymorphism here: 
- Fetching `/photos` sends an array of photo objects as primary data with the following characteristics:
  - `imageable_id` and `imageable_type` fields
    - I don't expect these fields to be included
  - `type` field for all is "photos"
    - Based on the above, I expect the type fields to be indicate the polymorphism (e.g. `type: book-photo`, `type: series-photo`, etc.)
  - `links` property includes an `imageable` object with links like `/photos/1/imageable`
    - querying this URL returns the resource that has this photo as its relation
    - While links back to the related resource make sense, I expect this to be linked based on the resource type (e.g. `books`), not `imageable`.

I'd be happy to PR this PR with failing integration tests, but the above are my assumptions, and we should figure out what the expected behavior should be first.

As a side note, since the spec is bending over backwards to sacrifice conciseness and clarity for the benefit of heterogeneous relationships, it would be nice to see a few more examples of what that should look like, because I'm not even sure what would be "correct."

**Comment by tkellen** [comment]
@bobholt Did you try http://localhost:8080/v1/photos?include=imageable?

**Comment by bobholt** [comment]
@tkellen I did `GET /photos` and `GET /photos/1/imageable` in the integration suite. 

Is imageable a thing that the api consumer is supposed to understand? It seems like an implementation detail Bookshelf uses to give the illusion of polymorphism while still using a strictly homogeneous database structure.

**Comment by tkellen** [comment]
@bobholt I haven't updated our formatter at all yet, this PR was purely to have this sort of data at all, so we can view the places where it falls over. I can address the first two failing pretty easily.  I'm unclear about the last.

**Comment by tkellen** [comment]
Ah, I know what to do re: the last.

**Comment by tkellen** [comment]
Also, FWIW, I don't have any intention of solving these issues now. I'd rather wait until someone in the community actually has a need for this.

**Comment by bobholt** [comment]
Taking this discussion off the public repo, unless you think it should be
there:

There's always another way :-)

Here's a multi-table example where the subtypes share a common abstract
type, and that type keeps a binary code to indicate which subtype it is.
It's a gross implementation (each activity is entered into 2 tables: the
abstract `Activity` and the subType), but I'd make that tradeoff for the
greater clarity of the relationships it provides as well making querying
specific subtypes easier.

[image: Inline image 1]

The Bookshelf/ActiveRecord way looks like a single type (photos) where the
subtype is a property of that type and the relationship is hard-coded into
the table as `imageable_id` in a to-One manner, even though this is
toMany/morphMany. That's confusing to me.

**Comment by tkellen** [comment]
Would you mind adding this comment back to that PR? I don't think I'll forget this use case but I want to make sure I cover it when I get a chance to take another stab at adding this polymorphic relation style to fantasy-database.

**Comment by tkellen** [comment]
From @dgeb in https://github.com/json-api/json-api/issues/278
> This will allow the spec to implicitly support polymorphism in what I've come to see as the only sane way: any resource types that may be mixed in a heterogenous collection must share an ID space. Implementations may choose to use UUIDs or perhaps a shared ID scheme and generator across types.

> By requiring a unique ID space for any types that may be mixed, we remove the need to specify both ID and type when modifying polymorphic relationships.

**Comment by bobholt** [comment]
--Previously-deleted comment--

There's always another way :-)

Here's a multi-table example where the subtypes share a common abstract type, and that type keeps a binary code to indicate which subtype it is. It's a gross implementation (each activity is entered into 2 tables: the abstract `Activity` and the subType), but I'd make that tradeoff for the greater clarity of the relationships it provides as well making querying specific subtypes easier.

polymorphic

The Bookshelf/ActiveRecord way looks like a single type (photos) where the subtype is a property of that type and the relationship is hard-coded into the table as `imageable_id` in a to-One manner, even though this is toMany/morphMany. That's confusing to me.

**Comment by tkellen** [comment]
Closing for now. This is being honed in on incrementally in other PRs.

**Pull request closed without merging**
