### PR TITLE
WIP: Work-in-silliness - http error library

### PR DESCRIPTION
**Pull request by bobholt**
I know there have to be libs out there that do stuff like this, but I wanted to play with writing one. Is this kind of what you were thinking of @tkellen? 

Still some cleanup to do if we want to go this route.

### CODE REVIEW

**Comment by tkellen** [comment]
Totally! The only thing I'd change is not actually throwing in Kapow, you'd do `throw Kapow(..)`.

I think this should be a top level module in the modules folder, to eventually be pulled out into its own thing!

**Comment by bobholt** [comment]
Not sure if it was obvious, but I wrote in a distinction so that this throws: `Kapow(400, 'That was a bad request');` and this just returns the error: `var err = Kapow[400]('That was a bad request');`

If you still don't ever want to throw in the lib, then I'll probably remove the second form and make Kapow a real constructor.

**Comment by tkellen** [comment]
The stack trace will be a lot more useful if you're required to throw the error that kapow gives you.


```js
// error.js
module.exports = function () {
  throw new Error('crap');
};

// thrower.js
var error = require('./error');

function go () {
  error();
};

go();
```

Produces (note the origin of the error appears to be in the error file (i.e. kapow):
```
/Users/tkellen/code/thrower/error.js:2
  throw new Error('crap');
        ^
Error: crap
    at module.exports (/Users/tkellen/code/thrower/error.js:2:9)
    at go (/Users/tkellen/code/thrower/thrower.js:4:3)
    at Object.<anonymous> (/Users/tkellen/code/thrower/thrower.js:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```
---

Switching it to this:
```js
// error.js
module.exports = function () {
  return new Error('crap');
};

// test.js
var error = require('./error');

function go () {
  throw error();
};

go();
```

Produces (note the origin of the error appears to be in the thrower file where it belongs):
```
/Users/tkellen/code/thrower/thrower.js:4
  throw error();
        ^
Error: crap
    at module.exports (/Users/tkellen/code/thrower/error.js:2:10)
    at go (/Users/tkellen/code/thrower/thrower.js:4:9)
    at Object.<anonymous> (/Users/tkellen/code/thrower/thrower.js:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by tkellen** [comment]
Also, side effects!

**Comment by bobholt** [comment]
lol, good points. fair enough.

**Comment by tkellen** [comment]
:dancers:

**Pull request merged**
