### PR TITLE
convert to es6

### PR DESCRIPTION
**Pull request by tkellen**
WIP. 

Shooting to have this done by EOD tomorrow. This is in preparation for supporting class extension (will support both `class MyController extends Endpoints.Controller` for es6 users and `var MyController = Endpoints.Controller.extend(...)` for es5 users)

### CODE REVIEW

**Comment by tkellen** [comment]
This is ready for review @bobholt.  This doesn't change any functionality, it's just a first pass to get babel compilation rolling. I'm using ES6 class syntax and lots of other sugar now. Once we land this I'll add support for extension.

**Comment by tkellen** [comment]
cc @jmeas I think I found a much easier way to do node libs using es6 functionality. Would you mind having a peek @ my package.json here to see if I'm missing something obvious?

**Comment by tkellen** [comment]
Also, I'm open to using the es6 module format, if you'd like, @bobholt.  Thoughts?

**Comment by tkellen** [comment]
@ashleygwilliams Once this lands you'll need to re-install jsdoc, this branch is running off of their master because none of the currently published versions support es6 class syntax.

**Comment by bobholt** [comment]
Tests pass, so :+1:.

I do like es6 module syntax. That's about all of ES6 I know though, so I'll be here if you need me: https://babeljs.io/docs/learn-es6/

**Comment by tkellen** [comment]
I was initially hesitant because support in v8 is really immature for modules, I'd thought we could just run this stuff without transpilation in iojs (and by proxy, in node, if the reconciliation ever happens :/), but that doesn't appear to be the case.  I'll update for es6 module syntax and then merge.

**Comment by bobholt** [comment]
I mean, I'm also okay waiting. No rush from me.

**Comment by tkellen** [comment]
Well, I updated it, but then found out jsdoc doesn't support module syntax yet.  Boo.  I'll keep it as a separate branch.

**Pull request merged**
