### PR TITLE
validate data sent to create/update for json-api compliance

### PR DESCRIPTION
**Pull request by bobholt**

### CODE REVIEW

**Comment by tkellen** [comment]
I'm :+1: to the verify step, but I feel like sanitization belongs in the source.

I think our source methods (create/update/delete) need to be smart enough to receive a json-api compliant object and do all the bookshelf methods need to deal with relations, etc. Thoughts?

**Comment by tkellen** [comment]
Also, this sanitization method will break down for sending compound documents.

**Comment by bobholt** [comment]
Putting the sanitization it in our source facade makes sense.

Under the base spec, only single data objects are allowed on a create or update. Supporting extensions is going to have to override the base spec in a lot more than just this method. (e.g. all of the content-type and accept header verification will have to allow for and check for specific extensions on request and response).

I guess I'm taking the TDD view and I'm willing to punt on it until we move to fully support the bulk extension.

**Comment by bobholt** [comment]
Moved sanitization to source.

I was tempted to just automatically delete any props that weren't on the source model, but it should be explicitly aware of what we're adding because of json-api, and error out when the user sends a prop that isn't on the model and not required by json-api.

**Comment by tkellen** [comment]
:+1: to erroring out on invalid props rather than silently removing them.

I was speaking with @bmac about this today. I've done a bunch of research into schema validation and I think incorporating json-schema definitions on the sources actually makes a ton of sense. This is basically a reversal of punting on route validation in endpoints issue #11.

This would gives us the "holy grail" of client-side validation using the same configuration as the server (and enhance our ability to self document / automate testing). Joi can't be used on the client without browserify, and the resulting file is pretty massive. It's also not based on a spec.

I'm pretty sure I want to use [is-my-json-valid](https://www.npmjs.com/package/is-my-json-valid).

ref: http://gilesbowkett.blogspot.com/2015/01/why-panda-strike-wrote-fastest-json.html
ref: https://www.pandastrike.com/posts/20150123-congrats-imjv

**Comment by tkellen** [comment]
Shoot, can you rebase this against master?

**Comment by bobholt** [comment]
rebased.

**Comment by tkellen** [comment]
:+1:

**Pull request merged**
